$ANSIBLE_VAULT;1.1;AES256
64313538306462616131663465383061663664356662373331663361623435313237376364656339
6439343866633662636234396661356638386630386236390a656662616532366230333462333431
66633266653964316165393337633837326665653632386131303233326163636435623137643731
3236376663303039630a363434316666623061336163333163393663613437376430353266393764
37383938356463376266636166653731623665363864363064613538323465343462663533353737
36346335643965326664353434636337373738386239656262633563643332303761383433343236
34313830353638336132666262303832313635313738303833613235633332346438386335323936
63393437383338343334313536363439316532363231646363643339646333623362333465373165
65363461303631633839333039323031393336613533326361393138313437353565
