- name: Create app directory
  become: true
  file:
    path: "{{ app_dir }}"
    state: directory
    mode: '0755'
    owner: deploy
    group: deploy

- name: Copy environment file from template
  template:
    src: env.j2
    dest: "{{ app_dir }}/.env"
    mode: '0600'
    owner: deploy
    group: deploy

- name: Copy docker compose file from template
  template:
    src: docker-compose.yml.j2
    dest: "{{ app_dir }}/docker-compose.yml"
    mode: '0600'
    owner: deploy
    group: deploy

