name: Discord bot CD


on:
  push:
    branches: ["main"]
    paths:
      - 'discord-bot/**'
      - '.github/workflows/cd_discord_bot.yml'
jobs:
  build_and_push_image:
    name: build-docker-image
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            discord-bot
            .github
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GH_PAT }}
        
      - name: Build and Push Discord Image
        uses: docker/build-push-action@v5
        with:
          context: ./discord-bot
          push: true
          tags: ghcr.io/${{secrets.GIT_USERNAME}}/sw-autoclaim-discord-bot:latest
          platforms: linux/arm64/v8
