name: Redemption service CD


on:
  push:
    branches: ["main"]
    paths:
      - 'redemption-service/**'
      - '.github/workflows/cd_redemption_service.yml'
jobs:
  build_and_push_image:
    name: build-docker-image
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            redemption-service
            .github
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GH_PAT }}
        
      - name: Build and Push Discord Image
        uses: docker/build-push-action@v5
        with:
          context: ./redemption-service
          push: true
          target: prod
          tags: ghcr.io/${{secrets.GIT_USERNAME}}/sw-autoclaim-redemption:latest
          platforms: linux/arm64/v8
